# Generated by Django 5.1.5 on 2025-02-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_cofferdata_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
    ]
