# Generated by Django 5.1.5 on 2025-02-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0003_delete_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofferdata',
            name='published',
            field=models.DateTimeField(null=True),
        ),
    ]
