# Generated by Django 5.1.5 on 2025-02-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0004_alter_cofferdata_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofferdata',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
