# Generated by Django 5.1.5 on 2025-02-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0005_alter_cofferdata_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofferdata',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
