# Generated by Django 5.1.5 on 2025-02-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0006_alter_cofferdata_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofferdata',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
