# Generated by Django 5.1.5 on 2025-02-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0007_alter_cofferdata_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofferdata',
            name='likelihood',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
