# Generated by Django 5.1.5 on 2025-02-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0008_alter_cofferdata_likelihood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofferdata',
            name='likelihood',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
