# Generated by Django 5.1.5 on 2025-02-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0010_alter_cofferdata_added_alter_cofferdata_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofferdata',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cofferdata',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
